kind = "web"
previewPath = "/"
title = "ECHO"
version = "1.0.0"
id = "artifacts/ECHO"
router = "path"

[[services]]
name = "web"
paths = [ "/" ]
localPort = 20148

[services.development]
run = "pnpm --filter @workspace/ECHO run dev"

[services.production]
build = [ "pnpm", "--filter", "@workspace/ECHO", "run", "build" ]
serve = "static"
publicDir = "artifacts/ECHO/dist/public"

[[services.production.rewrites]]
from = "/*"
to = "/index.html"

[services.env]
PORT = "20148"
BASE_PATH = "/"

