import hiTranslations from '../translations/hi.json';

// UI strings that need translation
export const UI_STRINGS = {
  // Common
  "EchoEdu": "EchoEdu",
  "Dashboard": "Dashboard",
  "AI Tutor": "AI Tutor",
  "Home": "Home",
  "Login": "Login",
  "Logout": "Logout",
  "Sign Up Free": "Sign Up Free",
  "Back": "Back",
  "Welcome back": "Welcome back",
  "Log in to continue learning": "Log in to continue learning",
  "Create your account": "Create your account",
  "Start your learning journey today": "Start your learning journey today",
  "Email": "Email",
  "Password": "Password",
  "Full Name": "Full Name",
  "Log In": "Log In",
  "Create Account": "Create Account",
  "Don't have an account?": "Don't have an account?",
  "Sign up free": "Sign up free",
  "Already have an account?": "Already have an account?",
  "Log in": "Log in",

  // HomePage
  "RESONATING WITH EVERY LEARNER": "RESONATING WITH EVERY LEARNER",
  "EchoEdu: The Voice of Every Child's Future.": "EchoEdu: The Voice of Every Child's Future.",
  "A voice-first AI tutor that turns any phone into a personal, gamified learning companion. Fully on-device, accessible, and designed for social good.": "A voice-first AI tutor that turns any phone into a personal, gamified learning companion. Fully on-device, accessible, and designed for social good.",
  "Join the Pilot": "Join the Pilot",
  "Watch Mission": "Watch Mission",
  "How it Works": "How it Works",
  "Three pillars designed to bridge the educational divide using the power of voice and edge AI.": "Three pillars designed to bridge the educational divide using the power of voice and edge AI.",
  "Voice-First Interaction": "Voice-First Interaction",
  "Designed from the ground up for blind and disabled children, prioritizing speech over complex visual UI.": "Designed from the ground up for blind and disabled children, prioritizing speech over complex visual UI.",
  "Simple & Intuitive": "Simple & Intuitive",
  "Designed to be easy to use, removing barriers to learning through voice interaction.": "Designed to be easy to use, removing barriers to learning through voice interaction.",
  "Gamified Learning": "Gamified Learning",
  "Turn every lesson into a quest. Education that feels like play, rewarding curiosity and consistent progress.": "Turn every lesson into a quest. Education that feels like play, rewarding curiosity and consistent progress.",
  "OUR MISSION": "OUR MISSION",
  "AI for Social Good.": "AI for Social Good.",
  "We believe that location, internet access, or physical ability should never be a barrier to quality education. EchoEdu is specifically optimized to run on $50 budget devices, bringing a world-class mentor to children in the most remote corners of the world.": "We believe that location, internet access, or physical ability should never be a barrier to quality education. EchoEdu is specifically optimized to run on $50 budget devices, bringing a world-class mentor to children in the most remote corners of the world.",
  "Children Targeted": "Children Targeted",
  "Offline Privacy": "Offline Privacy",
  "DESIGNED FOR ALL": "DESIGNED FOR ALL",
  "Radical Inclusivity in Learning": "Radical Inclusivity in Learning",
  "EchoEdu is purposefully built to break down barriers for blind, disabled, and underprivileged children worldwide.": "EchoEdu is purposefully built to break down barriers for blind, disabled, and underprivileged children worldwide.",
  "Screen-Reader Optimization": "Screen-Reader Optimization",
  "Native support for all major screen readers like VoiceOver and TalkBack. Every element is logically structured and annotated for perfect non-visual feedback.": "Native support for all major screen readers like VoiceOver and TalkBack. Every element is logically structured and annotated for perfect non-visual feedback.",
  "Voice-First Navigation": "Voice-First Navigation",
  "A revolutionary UI paradigm that requires zero visual interaction. Control the entire experience using natural language and intuitive vocal cues.": "A revolutionary UI paradigm that requires zero visual interaction. Control the entire experience using natural language and intuitive vocal cues.",
  "Indian Language Support": "Indian Language Support",
  "Ask questions and hear answers in Hindi, Tamil, Bengali, Telugu, Marathi, and 7 more Indian languages. AI answers in your chosen language.": "Ask questions and hear answers in Hindi, Tamil, Bengali, Telugu, Marathi, and 7 more Indian languages. AI answers in your chosen language.",
  "Offline Reliability": "Offline Reliability",
  "Powerful AI that runs on $50 budget devices without internet. We ensure no child is left behind due to the digital divide or lack of infrastructure.": "Powerful AI that runs on $50 budget devices without internet. We ensure no child is left behind due to the digital divide or lack of infrastructure.",
  "Ready to change the future of learning?": "Ready to change the future of learning?",
  "Join our early pilot program and help us bring the voice of education to those who need it most.": "Join our early pilot program and help us bring the voice of education to those who need it most.",
  "Join the Pilot Now": "Join the Pilot Now",
  "Resonating with every learner. Our voice-first AI is built to democratize education for every child, everywhere.": "Resonating with every learner. Our voice-first AI is built to democratize education for every child, everywhere.",
  "CONNECT WITH US": "CONNECT WITH US",

  // Dashboard
  "Skip to main content": "Skip to main content",
  "Navigation": "Navigation",
  "Go to home": "Go to home",
  "Main navigation": "Main navigation",
  "Accessibility settings": "Accessibility settings",
  "Accessibility": "Accessibility",
  "High Contrast": "High Contrast",
  "High Contrast: ON": "High Contrast: ON",
  "Switch Access": "Switch Access",
  "Switch Access: ON": "Switch Access: ON",
  "Text: Normal": "Text: Normal",
  "Text: Large": "Text: Large",
  "Text: X-Large": "Text: X-Large",
  "AMD infrastructure status": "AMD infrastructure status",
  "Powered by AMD EPYC Infrastructure": "Powered by AMD EPYC Infrastructure",
  "AI responds in <1s — real-time for every learner": "AI responds in <1s — real-time for every learner",
  "Welcome back": "Welcome back",
  "Ready to learn something new today?": "Ready to learn something new today?",
  "How to use your learning dashboard": "How to use your learning dashboard",
  "Use this guide to pick a language, choose a subject, explore chapters like an adventure, and ask your AI buddy your questions.": "Use this guide to pick a language, choose a subject, explore chapters like an adventure, and ask your AI buddy your questions.",
  "Pick your class": "Pick your class",
  "Choose a subject": "Choose a subject",
  "Open a chapter": "Open a chapter",
  "Ask your AI buddy": "Ask your AI buddy",
  "Pick a subject you love, like Maths, Science, or English.": "Pick a subject you love, like Maths, Science, or English.",
  "Choose a chapter from this subject so the AI can explain it like a story.": "Choose a chapter from this subject so the AI can explain it like a story.",
  "Type a question and watch the AI answer in a friendly way.": "Type a question and watch the AI answer in a friendly way.",
  "Example subjects": "Example subjects",
  "Chapter adventures": "Chapter adventures",
  "Ask any question": "Ask any question",
  "After choosing your subject and chapter, ask any question about what you are learning. The AI will explain it clearly.": "After choosing your subject and chapter, ask any question about what you are learning. The AI will explain it clearly.",
  "Math": "Math",
  "Science": "Science",
  "English": "English",
  "Chapter 1: Numbers and shapes": "Chapter 1: Numbers and shapes",
  "Chapter 2: Forces and motion": "Chapter 2: Forces and motion",
  "Chapter 3: Reading and writing": "Chapter 3: Reading and writing",
  "Free Plan": "Free Plan",
  "Premium": "Premium",
  "Unlock Premium Learning": "Unlock Premium Learning",
  "Get unlimited AI tutor sessions, all Indian languages support, priority responses, and advanced learning features.": "Get unlimited AI tutor sessions, all Indian languages support, priority responses, and advanced learning features.",
  "Unlimited AI chat sessions": "Unlimited AI chat sessions",
  "All 12 Indian languages": "All 12 Indian languages",
  "Priority AI responses — AMD accelerated": "Priority AI responses — AMD accelerated",
  "Upgrade to Premium — Free!": "Upgrade to Premium — Free!",
  "You're on Premium!": "You're on Premium!",
  "Enjoy unlimited access to all EchoEdu features.": "Enjoy unlimited access to all EchoEdu features.",
  "Quick actions": "Quick actions",
  "Chat with your personal AI tutor in any Indian language": "Chat with your personal AI tutor in any Indian language",
  "Start Learning →": "Start Learning →",
  "Voice Mode": "Voice Mode",
  "Speak your questions and hear answers in your language": "Speak your questions and hear answers in your language",
  "Try Voice →": "Try Voice →",
  "Language": "Language",
  "Learn in your preferred Indian language": "Learn in your preferred Indian language",
  "AMD Tech Career Learning Path": "AMD Tech Career Learning Path",
  "Explore technology topics that power the future — from chips to AI. Click any topic to start a conversation with your AI tutor!": "Explore technology topics that power the future — from chips to AI. Click any topic to start a conversation with your AI tutor!",
  "Account Details": "Account Details",
  "Name": "Name",
  "Plan": "Plan",
  "Free": "Free",
  "EchoEdu AI responses are formatted for Braille display compatibility. All text is plain Unicode for screen readers and Braille devices.": "EchoEdu AI responses are formatted for Braille display compatibility. All text is plain Unicode for screen readers and Braille devices.",
  "Skip to chat": "Skip to chat",
  "Child learning": "Child learning",
  "Mission illustration": "Mission illustration",
  "©2026 EchoEdu. Resonating with every learner.": "©2026 EchoEdu. Resonating with every learner.",
  "Change language": "Change language",

  // TutorPage
  "Go back to dashboard": "Go back to dashboard",
  "Back": "Back",
  "EchoEdu AI Tutor": "EchoEdu AI Tutor",
  "Hello! I am EchoEdu, your personal AI tutor. Ask me anything — I can answer in your chosen language!": "Hello! I am EchoEdu, your personal AI tutor. Ask me anything — I can answer in your chosen language!",
  "Ask anything in": "Ask anything in",
  "Type your question in": "Type your question in",
  "Send message": "Send message",
  "Press Enter to send • 🎤 for voice input": "Press Enter to send • 🎤 for voice input",
  "AI Tutor message": "AI Tutor message",
  "Your message": "Your message",
  "AI is thinking": "AI is thinking",
  "Failed to get a response. Check your API key.": "Failed to get a response. Check your API key.",
  "Edit your .env file and set VITE_GROQ_API_KEY": "Edit your .env file and set VITE_GROQ_API_KEY",

  // Gamification translations
  "chapters": "chapters",
  "Progress": "Progress",
  "points": "points",
  "Chapter": "Chapter",
  "Mark Complete": "Mark Complete",
  "Completed ✓": "Completed ✓",
  "Currently learning": "Currently learning",
  "Rewards Store": "Rewards Store",
  "Back to Tutor": "Back to Tutor",
  "Total Points": "Total Points",
  "Items Purchased": "Items Purchased",
  "Points Spent": "Points Spent",
  "Hint Boost": "Hint Boost",
  "Get extra hints during difficult questions": "Get extra hints during difficult questions",
  "Streak Freeze": "Streak Freeze",
  "Freeze your learning streak for 3 days": "Freeze your learning streak for 3 days",
  "Custom Avatar": "Custom Avatar",
  "Unlock a special profile avatar": "Unlock a special profile avatar",
  "Bonus Chapter": "Bonus Chapter",
  "Unlock an extra chapter in any subject": "Unlock an extra chapter in any subject",
  "Motivation Pack": "Motivation Pack",
  "Get personalized motivational messages": "Get personalized motivational messages",
  "Achievement Frame": "Achievement Frame",
  "Special frame for your profile achievements": "Special frame for your profile achievements",
  "Successfully purchased": "Successfully purchased",
  "Owned": "Owned",
  "Buy": "Buy",
  "Need Points": "Need Points",
  "Earn points by asking questions and completing chapters!": "Earn points by asking questions and completing chapters!",
  "Keep learning to unlock more rewards! 📚✨": "Keep learning to unlock more rewards! 📚✨",
  "Great questions! You're learning fast! 🚀": "Great questions! You're learning fast! 🚀",
  "Keep it up! You're becoming a subject expert! 📚": "Keep it up! You're becoming a subject expert! 📚",
  "Amazing curiosity! That's how champions learn! 🏆": "Amazing curiosity! That's how champions learn! 🏆",
  "You're on fire! Learning is your superpower! 🔥": "You're on fire! Learning is your superpower! 🔥",
  "Listening for voice input…": "Listening for voice input…",
  "Start voice input": "Start voice input",
  "Conversation": "Conversation",
  "AI responded in": "AI responded in",
  "Current language:": "Current language:",

  // Navbar
  "Features": "Features",
  "About": "About",
  "Accessibility": "Accessibility",

  // Auth forms
  "you@example.com": "you@example.com",
  "Your password": "Your password",
  "Your name": "Your name",
  "At least 6 characters": "At least 6 characters",
  "Choose Plan": "Choose Plan",
  "Basic AI tutor, limited sessions": "Basic AI tutor, limited sessions",
  "Unlimited sessions, all languages": "Unlimited sessions, all languages",
  "All fields are required.": "All fields are required.",
  "Password must be at least 6 characters.": "Password must be at least 6 characters.",
  "No account found. Please sign up.": "No account found. Please sign up.",
  "Email not found.": "Email not found.",
  "Incorrect password.": "Incorrect password.",

  // Pricing Page
  "Skip to pricing content": "Skip to pricing content",
  "Back to Dashboard": "Back to Dashboard",
  "Choose a plan that fits you": "Choose a plan that fits you",
  "Compare Free and Premium, then upgrade to unlock full AI support and accessibility tools.": "Compare Free and Premium, then upgrade to unlock full AI support and accessibility tools.",
  "Good for getting started": "Good for getting started",
  "Limited AI tutor sessions": "Limited AI tutor sessions",
  "Basic language support": "Basic language support",
  "Standard accessibility settings": "Standard accessibility settings",
  "Community learning tips": "Community learning tips",
  "Best for full learning support": "Best for full learning support",
  "Free upgrade": "Free upgrade",
  "All languages and faster responses": "All languages and faster responses",
  "Advanced accessibility features": "Advanced accessibility features",
  "Priority learning guidance": "Priority learning guidance",
  "Upgrade to Premium": "Upgrade to Premium",
  "Why Premium matters": "Why Premium matters",
  "Premium gives you a smoother AI experience with no session limits, faster answers, and smarter support for different learning needs.": "Premium gives you a smoother AI experience with no session limits, faster answers, and smarter support for different learning needs.",
  "Premium includes": "Premium includes",
  "Unlimited AI help for homework, concepts, and practice": "Unlimited AI help for homework, concepts, and practice",
  "Personalized responses for class level and subject": "Personalized responses for class level and subject",
  "Accessibility-ready interface for diverse learners": "Accessibility-ready interface for diverse learners",
  "Priority support and responsive tutor behavior": "Priority support and responsive tutor behavior",
  "Your accessibility setup": "Your accessibility setup",
  "We tailor EchoEdu based on your chosen preference:": "We tailor EchoEdu based on your chosen preference:",
  "What you struggle with": "What you struggle with",
  "What Premium adds": "What Premium adds",

  // Dashboard Additional
  "Hi": "Hi",
  "Toggle menu": "Toggle menu",
  "See Plans": "See Plans",
  "Unlimited sessions, all Indian languages, and priority AI responses.": "Unlimited sessions, all Indian languages, and priority AI responses.",
  "Normal": "Normal",
  "Large": "Large",
  "X-Large": "X-Large",
  "Rewards": "Rewards",

  // Account Page
  "Manage your profile and logout from here.": "Manage your profile and logout from here.",

  // Accessibility Categories
  "Cognitive Disabilities": "Cognitive Disabilities",
  "Low vision / Elderly": "Low vision / Elderly",
  "Hard of Hearing": "Hard of Hearing",
  "Limited Internet / Low Resources": "Limited Internet / Low Resources",
  "Complex text": "Complex text",
  "Too much information at once": "Too much information at once",
  "Distractions": "Distractions",
  "Simple mode UI": "Simple mode UI",
  "Text simplification": "Text simplification",
  "Focus mode": "Focus mode",
  "Icons + visuals": "Icons + visuals",
  "Better visibility, not full audio": "Better visibility, not full audio",
  "High contrast mode": "High contrast mode",
  "Font size control": "Font size control",
  "Dark/light themes": "Dark/light themes",
  "Zoom support": "Zoom support",
  "Partial audio support": "Partial audio support",
  "Captions": "Captions",
  "Adjustable audio speed": "Adjustable audio speed",
  "Volume boost": "Volume boost",
  "Clarity controls": "Clarity controls",
  "No stable internet": "No stable internet",
  "Low-end devices": "Low-end devices",
  "Offline mode": "Offline mode",
  "Low-data mode": "Low-data mode",
  "Text-first fallback": "Text-first fallback",
};

const LOCAL_TRANSLATIONS = {
  hi: hiTranslations,
};

export async function translateText(text, targetLangCode) {
  if (targetLangCode === 'en') return text;
  const resource = LOCAL_TRANSLATIONS[targetLangCode];
  return resource?.[text] || text;
}

// Hook for getting translated UI text
export function useTranslation() {
  // This will be implemented as a React hook
  return (key) => key; // Placeholder - actual implementation in hooks/useTranslation.js
}